- id: 1
  name: Shenzhen Stock Exchange
  symbol: SZ
- id: 2
  name: Shanghai Stock Exchange
  symbol: SS
- id: 3
  name: New York Stock Exchange
  symbol: NYSE
- id: 4
  name: NASDAQ Stock Exchange
  symbol: NASDAQ
- id: 5
  name: Toronto Stock Exchange
  symbol: TSX